"""
Pydantic Schemas for Formatter Agent
======================================

Defines validation schemas for all LLM outputs and formatter components.
"""

from pydantic import BaseModel, Field, field_validator, model_validator
from typing import List, Dict, Any, Literal, Optional


# ==============================================================================
# Executive Summary Schemas
# ==============================================================================


class ExecutiveSummaryOutput(BaseModel):
    """Schema for executive summary generated by LLM."""

    title: str = Field(
        ...,
        max_length=80,
        description="Concise professional title capturing analysis essence",
    )
    introduction: str = Field(
        ...,
        min_length=50,
        max_length=300,
        description="Contextual introduction paragraph (2-3 sentences)",
    )

    @field_validator("title")
    @classmethod
    def validate_title_not_empty(cls, v: str) -> str:
        """Ensure title is not just whitespace."""
        if not v.strip():
            raise ValueError("Title cannot be empty or whitespace")
        return v.strip()

    @field_validator("introduction")
    @classmethod
    def validate_introduction_not_empty(cls, v: str) -> str:
        """Ensure introduction is not just whitespace."""
        if not v.strip():
            raise ValueError("Introduction cannot be empty or whitespace")
        return v.strip()


# ==============================================================================
# Insight Synthesis Schemas
# ==============================================================================


class SynthesizedInsightsOutput(BaseModel):
    """Schema for synthesized insights generated by LLM."""

    narrative: str = Field(
        ...,
        min_length=400,
        max_length=800,
        description="Cohesive executive narrative connecting key insights (400-800 chars)",
    )
    key_findings: List[str] = Field(
        ...,
        min_length=3,
        max_length=5,
        description="3-5 concise bullet points with key findings",
    )

    @field_validator("narrative")
    @classmethod
    def validate_narrative_not_empty(cls, v: str) -> str:
        """Ensure narrative is not just whitespace."""
        if not v.strip():
            raise ValueError("Narrative cannot be empty or whitespace")
        return v.strip()

    @model_validator(mode="after")
    def validate_key_findings_length(self) -> "SynthesizedInsightsOutput":
        """Ensure each key finding is within character limits."""
        for i, finding in enumerate(self.key_findings):
            if not finding.strip():
                raise ValueError(f"Key finding {i + 1} cannot be empty")
            if len(finding) > 140:
                raise ValueError(
                    f"Key finding {i + 1} exceeds 140 characters: {len(finding)} chars"
                )
        return self


# ==============================================================================
# Next Steps Schemas
# ==============================================================================


class NextStepsOutput(BaseModel):
    """Schema for next steps recommendations generated by LLM."""

    next_steps: List[str] = Field(
        ...,
        min_length=3,
        max_length=3,
        description="Exactly 3 direct and actionable strategic next steps",
    )

    @model_validator(mode="after")
    def validate_next_steps_length(self) -> "NextStepsOutput":
        """Ensure each next step is within character limits and not empty."""
        for i, step in enumerate(self.next_steps):
            if not step.strip():
                raise ValueError(f"Next step {i + 1} cannot be empty")
            if len(step) > 200:
                raise ValueError(
                    f"Next step {i + 1} exceeds 200 characters: {len(step)} chars"
                )
        return self


# ==============================================================================
# Complete Formatter Output Schema
# ==============================================================================


class FormatterOutputSchema(BaseModel):
    """Complete schema for formatter agent output (for validation purposes)."""

    status: Literal["success", "error", "partial"]
    format_version: str
    timestamp: str
    executive_summary: Dict[str, Any]
    visualization: Dict[str, Any]
    insights: Dict[str, Any]
    next_steps: Dict[str, Any]
    data: Dict[str, Any]
    metadata: Dict[str, Any]
    error: Optional[Dict[str, Any]] = None

    class Config:
        extra = "allow"  # Allow additional fields for flexibility
